Repository SyTW2223/E02, pull requests merged in 2022-12, with the labels that each got.

#45 [#184016344]-deployment
  .github/workflows/deployBackend.yml
  Front-end/src/_services/user.service.ts
Labels: enhancement

#46 [#184016344]-deployment-bug
  .github/workflows/deployBackend.yml
  Front-end/.gitignore
  Front-end/package-lock.json
  Front-end/package.json
  Front-end/src/_services/user.service.ts
  Front-end/vite.config.ts
Labels: bug

#51 Update deployFront.yml to production
  .github/workflows/deployFront.yml
Labels: enhancement

#53 [#184046259]-sonarcloud
  .github/workflows/sonarcloud.yml
Labels: documentation, enhancement

#57 [#184090347] feature tienda browser
  Back-end/src/routers/panRoute.ts
  Front-end/src/App.tsx
  Front-end/src/components/Card/Card.tsx
  Front-end/src/components/Card/CardDisplay.tsx
  Front-end/src/components/Tienda/Tienda.tsx
  Front-end/test/Tienda.test.tsx
Labels: bug, enhancement

#58 #184085180 fix login
  Back-end/src/Controllers/PanData/panDataModel.ts
  Back-end/src/Controllers/UsuarioData/carteraDataModel.ts
  Back-end/src/Controllers/UsuarioData/direccionDataModel.ts
  Back-end/src/Controllers/UsuarioData/usuarioDataModel.ts
  Back-end/src/models/pan/pan.ts
  Back-end/src/test/app.test.ts
  Front-end/index.html
  Front-end/package-lock.json
  Front-end/src/App.tsx
  Front-end/src/_services/user.service.ts
  Front-end/src/components/Direccion.tsx
  Front-end/src/components/Footer.tsx
  Front-end/src/components/Home.tsx
  Front-end/src/components/Login.tsx
  Front-end/src/components/PanData.tsx
  Front-end/src/components/Profile.tsx
  Front-end/src/components/ProfileGucci.tsx
  Front-end/test/Home.test.tsx
Labels: bug, documentation

#59 Añadiendo características
  Back-end/package-lock.json
  Back-end/package.json
  README.md
Labels: bug

#64 [184102178]-bug-locastorage
  Front-end/src/_services/user.service.ts
Labels: bug

#65 [184102178]-bug
  Front-end/src/_services/user.service.ts
Labels: bug

#70 [184126967]-bug fixes
  Front-end/src/_actions/user.actions.ts
  Front-end/src/_helpers/history.ts
  Front-end/src/_services/user.service.ts
  Front-end/src/components/Home/Navbar.tsx
  Front-end/src/components/Login.tsx
  Front-end/src/components/Tienda/Carrito.tsx
  Front-end/src/components/Tienda/PanData.tsx
  Front-end/src/components/Tienda/Tienda.tsx
Labels: bug, enhancement
